--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=886945), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\Python\\Httprunner_Demo\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 222, 'message': 'Start to run testcase: yml测试用例, TestCase ID: d38dc202-71b5-4bdd-a5f6-11efd5e307fb', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=21792, name='MainProcess'), 'thread': (id=21272, name='MainThread'), 'time': datetime(2023, 5, 23, 16, 50, 58, 813408, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_simple_sinks.py", line 16, in write
    self._stream.write(message)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 204, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] 句柄无效。
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=889936), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\Python\\Httprunner_Demo\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 181, 'message': 'run step begin: yml测试用例 >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=21792, name='MainProcess'), 'thread': (id=21272, name='MainThread'), 'time': datetime(2023, 5, 23, 16, 50, 58, 816399, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_simple_sinks.py", line 16, in write
    self._stream.write(message)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 204, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] 句柄无效。
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=956882), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\Python\\Httprunner_Demo\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 216, 'message': 'status_code: 200, response_time(ms): 62.45 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=21792, name='MainProcess'), 'thread': (id=21272, name='MainThread'), 'time': datetime(2023, 5, 23, 16, 50, 58, 883345, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_simple_sinks.py", line 16, in write
    self._stream.write(message)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 204, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] 句柄无效。
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=958804), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\Python\\Httprunner_Demo\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 230, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=21792, name='MainProcess'), 'thread': (id=21272, name='MainThread'), 'time': datetime(2023, 5, 23, 16, 50, 58, 885267, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_simple_sinks.py", line 16, in write
    self._stream.write(message)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 204, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] 句柄无效。
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=959804), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\Python\\Httprunner_Demo\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 230, 'message': 'assert body.code equal 412(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=21792, name='MainProcess'), 'thread': (id=21272, name='MainThread'), 'time': datetime(2023, 5, 23, 16, 50, 58, 886267, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_simple_sinks.py", line 16, in write
    self._stream.write(message)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 204, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] 句柄无效。
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=960801), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\Python\\Httprunner_Demo\\httprunner\\response.py'), 'function': 'validate', 'level': (name='ERROR', no=40, icon='❌'), 'line': 247, 'message': 'assert $..code equal [412](list)\t==> fail\ncheck_item: $..code\ncheck_value: $..code(str)\nassert_method: equal\nexpect_value: [412](list)', 'module': 'response', 'name': 'httprunner.response', 'process': (id=21792, name='MainProcess'), 'thread': (id=21272, name='MainThread'), 'time': datetime(2023, 5, 23, 16, 50, 58, 887264, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\Python\Httprunner_Demo\httprunner\response.py", line 228, in validate
    assert_func(check_value, expect_value, message)
  File "D:\Python\Httprunner_Demo\httprunner\builtin\comparators.py", line 10, in equal
    assert check_value == expect_value, message
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_simple_sinks.py", line 16, in write
    self._stream.write(message)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 204, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] 句柄无效。
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=962796), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\Python\\Httprunner_Demo\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 233, 'message': 'generate testcase log: D:\\Python\\Httprunner_Demo\\demo\\logs\\d38dc202-71b5-4bdd-a5f6-11efd5e307fb.run.log', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=21792, name='MainProcess'), 'thread': (id=21272, name='MainThread'), 'time': datetime(2023, 5, 23, 16, 50, 58, 889259, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\Python\Httprunner_Demo\httprunner\runner.py", line 231, in test_start
    self.__run_step(step)
  File "D:\Python\Httprunner_Demo\httprunner\runner.py", line 188, in __run_step
    step_result: StepResult = step.run(self)
  File "D:\Python\Httprunner_Demo\httprunner\step.py", line 67, in run
    return self.__step.run(runner)
  File "D:\Python\Httprunner_Demo\httprunner\step_request.py", line 348, in run
    return run_step_request(runner, self.__step)
  File "D:\Python\Httprunner_Demo\httprunner\step_request.py", line 176, in run_step_request
    resp_obj.validate(validators, variables_mapping)
  File "D:\Python\Httprunner_Demo\httprunner\response.py", line 254, in validate
    raise ValidationFailure(failures_string)
httprunner.exceptions.ValidationFailure: assert $..code equal [412](list)	==> fail
check_item: $..code
check_value: $..code(str)
assert_method: equal
expect_value: [412](list)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\loguru\_simple_sinks.py", line 16, in write
    self._stream.write(message)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 195, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\mengzhang32\.virtualenvs\HttpRunner_Demo-yEqEqPDM\lib\site-packages\colorama\ansitowin32.py", line 204, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] 句柄无效。
--- End of logging error ---
